# Generated by Django 3.2.16 on 2022-11-27 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from apps.material.models.utils.file import material_file_directory_path


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "is_paid",
                    models.BooleanField(default=True, verbose_name="Is Paid"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="The day and time the live will start",
                        verbose_name="Starts At",
                    ),
                ),
                (
                    "integration_field",
                    models.TextField(
                        help_text=(
                            "This field controls the integration that will be made "
                            "for the Live to happen. Fields like Youtube ID, Vimeo ID, "
                            "Zoom JSON, etc are accepted."
                        ),
                        verbose_name="Integration Field",
                    ),
                ),
                (
                    "live_type",
                    models.CharField(
                        choices=[
                            ("live_class", "Live Class"),
                            ("interactive_class", "Interactive Class"),
                        ],
                        default="live_class",
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=material_file_directory_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lives",
                        to="service.servicemodel",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live",
                "verbose_name_plural": "Lives",
            },
        ),
    ]
