# Generated by Django 3.2.18 on 2023-05-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0024_auto_20230523_1609"),
        ("service", "0002_serviceclientmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceemailconfigmodel",
            name="email_sender",
            field=models.CharField(
                choices=[("sendgrid", "Sendgrid"), ("dummy", "Dummy")],
                default="dummy",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serviceemailconfigmodel",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_configs",
                to="social.eventmodel",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="serviceemailconfigmodel",
            name="email_config_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                    ("guest_invitation", "Guest Invitation"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="serviceemailconfigmodel",
            name="email_link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
    ]
