# Generated by Django 3.2.18 on 2023-05-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_auto_20230523_1609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceemailconfigmodel",
            name="email_html_template",
            field=models.TextField(
                help_text=(
                    "You can use the following variables: "
                    "<br>[FIRST_NAME] "
                    "<br>[LAST_NAME] "
                    "<br>[USERNAME] "
                    "<br>[EMAIL] "
                    "<br>[TOKEN] "
                    "<br>[SERVICE_NAME] "
                    "<br>[EVENT_NAME] "
                    "<br>[GUEST_PASSWORD] "
                    "<br>"
                ),
                verbose_name="HTML Template",
            ),
        ),
        migrations.AlterField(
            model_name="serviceemailconfigmodel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_configs",
                to="service.servicemodel",
                verbose_name="Service",
            ),
        ),
    ]
