# Generated by Django 3.2.19 on 2023-06-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_auto_20230523_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceemailconfigmodel",
            name="email_config_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                    ("guest_invitation", "Guest Invitation"),
                    ("mention_notification", "Mention Notification"),
                ],
                max_length=255,
            ),
        ),
    ]
