# Generated by Django 3.2.25 on 2024-04-07 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_serviceemailconfigmodel_email_config_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialGraphProviderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date modified"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Social Graph Provider",
                "verbose_name_plural": "Social Graph Providers",
            },
        ),
        migrations.AlterField(
            model_name="serviceemailconfigmodel",
            name="email_config_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                    ("guest_invitation", "Guest Invitation"),
                    ("mention_notification", "Mention Notification"),
                    ("new_post_notification", "New Post Notification"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="SocialGraphModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date modified"
                    ),
                ),
                (
                    "searcher",
                    models.CharField(
                        help_text=(
                            "The search engine that will " "be used to search for data"
                        ),
                        max_length=255,
                        verbose_name="Searcher",
                    ),
                ),
                (
                    "graph_image",
                    models.URLField(blank=True, null=True, verbose_name="Graph Image"),
                ),
                (
                    "provider",
                    models.ManyToManyField(
                        blank=True,
                        related_name="social_graphs",
                        to="service.SocialGraphProviderModel",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_graphs",
                        to="service.servicemodel",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Graph",
                "verbose_name_plural": "Social Graphs",
            },
        ),
    ]
