# Generated by Django 3.2.25 on 2024-04-07 07:08

from django.db import migrations


def create_default_providers(apps, _schema_editor):
    social_graph_provider_model = apps.get_model("service", "SocialGraphProviderModel")
    default_providers = ["Twitter", "Facebook", "Instagram", "LinkedIn"]

    for provider_name in default_providers:
        social_graph_provider_model.objects.create(name=provider_name)


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_auto_20240407_0707"),
    ]

    operations = [
        migrations.RunPython(create_default_providers),
    ]
