# Generated by Django 3.2.16 on 2023-04-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_auto_20230419_1238"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="social.eventmodel",
                verbose_name="Event",
            ),
        ),
    ]
