# Generated by Django 3.2.25 on 2024-04-07 07:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visual_structure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colormodel",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
