# Generated by Django 3.2.16 on 2022-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buying", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storemodel",
            name="backend",
            field=models.CharField(
                choices=[("dummy", "Dummy Backend"), ("apple", "Apple Backend")],
                max_length=255,
                verbose_name="Integration Backend",
            ),
        ),
    ]
