# Generated by Django 3.2.16 on 2023-04-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_eventmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="social.eventmodel",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="guests",
            field=models.TextField(
                blank=True,
                help_text="\n\n            Enter guests in the following format:\n\n            email,password\n            email,password\n            email,password\n            ...\n        ",
                null=True,
                verbose_name="Guests",
            ),
        ),
    ]
