# Generated by Django 3.2.16 on 2023-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_auto_20230419_0241"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="send_email_to_guests",
            field=models.BooleanField(
                default=False, verbose_name="Send email to guests"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="guests",
            field=models.TextField(
                blank=True,
                help_text="\n            Enter guests in the following format:\n            <br>\n            email,password<br>\n            email,password<br>\n            email,password\n            ...\n        ",
                null=True,
                verbose_name="Guests",
            ),
        ),
    ]
