# Generated by Django 3.2.16 on 2023-04-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_auto_20230419_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcommentmodel",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="social.postmodel",
                verbose_name="Post",
            ),
        ),
    ]
