# Generated by Django 3.2.18 on 2023-04-26 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.social.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0008_alter_postcommentmodel_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image"), ("video", "Video")],
                default="text",
                max_length=255,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.social.models.event_directory_path,
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="postcommentmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
    ]
