# Generated by Django 3.2.18 on 2023-04-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_serviceclientmodel"),
        ("social", "0011_auto_20230426_2257"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionmodel",
            name="service_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="service.serviceclientmodel",
                verbose_name="Service Client",
            ),
        ),
    ]
