# Generated by Django 3.2.18 on 2023-04-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0013_auto_20230427_0130"),
    ]

    operations = [
        migrations.AddField(
            model_name="missioninteractionmodel",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="loginquestions",
            name="question",
            field=models.CharField(
                help_text=(
                    "Tip: use the 'Save and add another' "
                    "option to keep adding questions."
                ),
                max_length=255,
                verbose_name="Question",
            ),
        ),
    ]
