# Generated by Django 3.2.18 on 2023-05-01 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0014_auto_20230427_0146"),
    ]

    operations = [
        migrations.CreateModel(
            name="IATextReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("pre_set", models.TextField(verbose_name="Pre Set")),
                (
                    "chat_ai",
                    models.CharField(
                        choices=[("dummy", "Dummy"), ("gpt-3", "GPT-3")],
                        default="dummy",
                        max_length=255,
                        verbose_name="Chat AI",
                    ),
                ),
            ],
            options={
                "verbose_name": "IA Text Report",
                "verbose_name_plural": "IA Text Reports",
            },
        ),
        migrations.AddField(
            model_name="postmodel",
            name="ia_report",
            field=models.TextField(blank=True, null=True, verbose_name="IA Report"),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="ia_text_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="social.iatextreportmodel",
                verbose_name="IA Text Report",
            ),
        ),
    ]
