# Generated by Django 3.2.18 on 2023-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_auto_20230501_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactiontypemodel",
            name="name",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("dislike", "Dislike"),
                    ("love", "Love"),
                    ("haha", "Haha"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                ],
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
