# Generated by Django 3.2.18 on 2023-05-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0019_remove_postmodel_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missioninteractionmodel",
            options={
                "verbose_name": "User Mission",
                "verbose_name_plural": "User Missions",
            },
        ),
        migrations.AlterModelOptions(
            name="postcommentmodel",
            options={
                "verbose_name": "User Comment",
                "verbose_name_plural": "User Comments",
            },
        ),
    ]
