# Generated by Django 3.2.18 on 2023-05-20 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0020_auto_20230520_0352"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Mission Type",
                "verbose_name_plural": "Mission Types",
            },
        ),
        migrations.RemoveField(
            model_name="missionmodel",
            name="type",
        ),
        migrations.AddField(
            model_name="missionmodel",
            name="type",
            field=models.ManyToManyField(
                to="social.MissionTypeModel", verbose_name="Type"
            ),
        ),
    ]
