# Generated by Django 3.2.18 on 2023-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0021_auto_20230520_0409"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionmodel",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="missionmodel",
            name="type",
            field=models.ManyToManyField(
                related_name="missions",
                to="social.MissionTypeModel",
                verbose_name="Type",
            ),
        ),
    ]
