# Generated by Django 3.2.18 on 2023-05-23 01:05

from django.db import migrations, models

import apps.social.models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0022_auto_20230522_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionmodel",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                help_text=(
                    "Thumbnail for the mission video, if the attachment is a video"
                ),
                null=True,
                upload_to=apps.social.models.mission_directory_path,
                verbose_name="Thumbnail",
            ),
        ),
    ]
