# Generated by Django 3.2.18 on 2023-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0024_auto_20230523_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcommentmodel",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="guests",
            field=models.TextField(
                blank=True,
                help_text=(
                    "\n            Enter guests in the following format:"
                    "\n            <br>"
                    "\n            name;email,name;email,name;email,name;email,..."
                    "\n            <br>"
                    "\n            Like:"
                    "\n            <br>"
                    "\n            John Doe;john@mail.com,Elisa Jax;elisa@mail."
                    "com,Edward,edward.us@mail.com,...\n        "
                ),
                null=True,
                verbose_name="Guests",
            ),
        ),
    ]
