# Generated by Django 3.2.18 on 2023-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0026_reactiontypemodel_clicked_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missiontypemodel",
            name="name",
            field=models.CharField(
                choices=[("video", "Video"), ("audio", "Audio"), ("text", "Text")],
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
