# Generated by Django 3.2.18 on 2023-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0027_alter_missiontypemodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missiontypemodel",
            name="name",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Image", "Image"),
                    ("Audio", "Audio"),
                    ("Text", "Text"),
                ],
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
