# Generated by Django 3.2.19 on 2023-06-16 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0028_alter_missiontypemodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcommentmodel",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_comments_mentions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mentions",
            ),
        ),
    ]
