# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Delivery to Production

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_PRD_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PRD_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_PRD_DB }}
  DB_HOST: ${{ secrets.POSTGRES_PRD_HOST }}
  DB_PORT: ${{ secrets.POSTGRES_PRD_PORT }}

  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD_PRD }}

  APPLE_SECRET_KEY: ${{ secrets.APPLE_SECRET_KEY }}
  APPLE_SHARED_SECRET: ${{ secrets.APPLE_SHARED_SECRET }}

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SLACK_MESSAGE_URL: ${{ secrets.SLACK_MESSAGE_URL }}

  ENVIRONMENT: prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Zappa Deploy to Production
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Building Environment
      run: |
        echo POSTGRES_USER=${{ secrets.POSTGRES_PRD_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PRD_PASSWORD }} >> .env
        echo POSTGRES_DB=${{ secrets.POSTGRES_PRD_DB }} >> .env
        echo DB_HOST=${{ secrets.POSTGRES_PRD_HOST }} >> .env
        echo DB_PORT=${{ secrets.POSTGRES_PRD_PORT }} >> .env
        echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD_PRD }} >> .env
        echo APPLE_SECRET_KEY=${{ secrets.APPLE_SHARED_SECRET }} >> .env
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
        echo SLACK_MESSAGE_URL=${{ secrets.SLACK_MESSAGE_URL }} >> .env
        echo OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }} >> .env
        echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> .env
        echo ENVIRONMENT=prod >> .env

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
    - name: Configure AWS
      run: |
        source venv/bin/activate
        aws configure set region us-east-2
        aws configure set output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Send slack message
      run: |
        source venv/bin/activate
        python ./scripts/slack_message.py "[All Line] 🧪 Deploy iniciado para o ambiente: Production"

    - name: Deploying
      run: |
        source venv/bin/activate
        zappa update prd && python ./scripts/slack_message.py "[All Line] ✅ Deploy feito com sucesso" || python ./scripts/slack_message.py "[All Line] ❌ Deploy falhou"

    - name: Migrating the database
      run: |
        source venv/bin/activate
        zappa manage prd migrate
