# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Delivery to Production

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Zappa Deploy to Production
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/tests.txt
    - name: Deploying
      run: |
        zappa update prd
